# Generated by Django 4.1.4 on 2023-05-16 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='productsshop',
            options={'verbose_name': 'Продукты в магазине', 'verbose_name_plural': 'Продукты в магазинах'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='productsshop',
            name='subcategory',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='products_shop', to='products.subcategory', verbose_name='Выберите категорию'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='brands_logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products_images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(upload_to='shops_logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category', verbose_name='Выберите категорию'),
        ),
    ]
